# Generated by Django 5.1 on 2024-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1024)),
                ('length', models.DurationField()),
                ('size', models.IntegerField()),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField()),
            ],
        ),
    ]
