# Generated by Django 5.1 on 2024-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
