# Generated by Django 5.1 on 2024-08-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0002_alter_mediafile_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='transcript',
            field=models.TextField(blank=True, default='blank'),
            preserve_default=False,
        ),
    ]
