# Generated by Django 5.1 on 2024-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0003_alter_mediafile_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
