# Generated by Django 5.1 on 2024-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0004_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
    ]
