# Generated by Django 5.1 on 2024-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0005_mediafile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
