# Generated by Django 5.1 on 2024-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock_videos', '0009_alter_mediafile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
